name: 'Monday App Import'
description: 'Import app from manifest file'
inputs:
  token:
    description: 'Monday developer token'
    required: true
  appId:
    description: 'The ID of your monday app'
    required: false
  versionId:
    description: 'The version ID of your monday app'
    required: false
  new:
    description: 'Create new app'
    required: false
    default: false
  manifestPath:
    description: 'Path to the manifest file'
    required: true
  promote:
    description: 'Promote the version to Live'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.token }}
  - ${{ inputs.appId }}
  - ${{ inputs.versionId }}
  - ${{ inputs.new }}
  - ${{ inputs.manifestPath }}
  - ${{ inputs.promote }}
